### ISSUE TITLE
[NOT LOAD] Could not load 好像是缺少前置

### ISSUE THREAD

**Issue by Kaesong-Nan** [SAGESSE-CN/Armourers-Workshop-Plugin#11]
[23:50:01] [Server thread/ERROR]: Could not load 'plugins\armourersworkshop-plugin-2.1.0.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency cocoon. Please download and install cocoon to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:269) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:414) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:224) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
        at java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by Kaesong-Nan** [comment]
[在这里构建了 前置 Cocoon](https://github.com/SAGESSE-CN/Cocoon)
插件指令用起来没有任何提示，按tab补充进行了操作
测试版本：Spigot 1.19.2
以下是使用反馈：
1. 服务端中的时装下载到客户端速度很慢，几乎没有反应
2. 直接添加到客户端的时装文件，使用giveskin可以获取物品，但物品不显示时装，只有鼠标悬浮时装框
3. 时装文件不知道如何使用，/armourers openWardrobe 指令没有效果，服务端也没有任何反馈
4. 使用/armourers setSkin 设置了直接添加到客户端的时装，切换第三人称视角可以查看，第一人称手臂无显示变化

**Comment by SAGESSE-CN** [comment]
1. 如果它最终能下载成功，这说明是你的网络确实慢，这无解，但每个玩家只需要下载一次

2. 客户端也需要安装cocoon, 说明页有写

4. 客户端也需要安装cocoon, 说明页有写

5. 第一人称渲染需要你在配置文件中渲染

**Comment by SAGESSE-CN** [comment]
https://modrinth.com/plugin/armourers-workshop-plugin

**Comment by Kaesong-Nan** [comment]
[modrinth 论坛（点击下载）](https://modrinth.com/plugin/armourers-workshop-plugin)
