### ISSUE TITLE
error

### ISSUE THREAD

**Issue by binqidada** [SAGESSE-CN/Armourers-Workshop-Plugin#12]
[00:48:32 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins\armourersworkshop-plugin-2.1.0.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [cocoon]. Please download and install these plugins to run 'armourers_workshop'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Kaesong-Nan** [comment]
如何使用：
对于插件服务器所有者：

安装任何 bukkit 服务器

安装[Cocoon 服务器库](https://modrinth.com/plugin/cocoon/versions?l=bukkit)

安装[Armourer's Workshop 插件](https://modrinth.com/plugin/armourers-workshop-plugin/versions)

对于插件服务器的客户端用户：

安装 fabirc/forge 客户端

安装[Cocoon Client Library ](https://modrinth.com/plugin/cocoon/versions?l=fabric&l=forge)<--重要

安装[Armourer's Workshop Mod](https://modrinth.com/mod/armourers-workshop/versions)


- from https://modrinth.com/plugin/armourers-workshop-plugin

**Comment by SAGESSE-CN** [comment]
请流程安装指南

https://modrinth.com/plugin/armourers-workshop-plugin

**Comment by SAGESSE-CN** [comment]
pls flow install [guide](https://modrinth.com/plugin/armourers-workshop-plugin), and we not support 1.20.4 now.

**Comment by binqidada** [comment]
Can you get a cocoon server that supports 1.20.4 to start

**Comment by binqidada** [comment]
[01:06:46 ERROR]: Error occurred while enabling cocoon v2.0.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at net.cocoonmc.runtime.impl.CocoonPluginImpl.onEnable(CocoonPluginImpl.java:11) ~[cocoon-2.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Cocoon does not support server version "v1_20_R3"
        at net.cocoonmc.runtime.IRuntimeLoader.load(IRuntimeLoader.java:28) ~[cocoon-2.0.1.jar:?]
        at net.cocoonmc.Cocoon.<clinit>(Cocoon.java:27) ~[cocoon-2.0.1.jar:?]
        ... 13 more
Caused by: java.lang.ClassNotFoundException: net.cocoonmc.runtime.v1_20_R3.RuntimeFactory
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:421) ~[?:?]
        at java.lang.Class.forName(Class.java:412) ~[?:?]
        at net.cocoonmc.runtime.IRuntimeLoader.load(IRuntimeLoader.java:24) ~[cocoon-2.0.1.jar:?]
        at net.cocoonmc.Cocoon.<clinit>(Cocoon.java:27) ~[cocoon-2.0.1.jar:?]
        ... 13 more

**Comment by binqidada** [comment]
I want to use a 1.20.1 server to get into a 1.20.4 server

**Comment by SAGESSE-CN** [comment]
1.20.4 have lot of technical changes.
