### ISSUE TITLE
Server thread/ERROR

### ISSUE THREAD

**Issue by Kaesong-Nan** [SAGESSE-CN/Armourers-Workshop-Plugin#13]
```
[Server thread/ERROR]: Error occurred while enabling armourers_workshop v2.1.1 (Is it up to date?)
java.lang.RuntimeException: java.lang.NullPointerException: Cannot read the array length because "<local1>" is null
        at moe.plushie.armourers_workshop.core.data.DataManager.connect(DataManager.java:45) ~[?:?]
        at moe.plushie.armourers_workshop.ArmourersWorkshopPlugin.onEnable(ArmourersWorkshopPlugin.java:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:546) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:460) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:588) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:413) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local1>" is null
        at moe.plushie.armourers_workshop.core.data.source.SkinFileDataSource$Local.loadNodes(SkinFileDataSource.java:226) ~[?:?]
        at moe.plushie.armourers_workshop.core.data.source.SkinFileDataSource$Local.connect(SkinFileDataSource.java:173) ~[?:?]
        at moe.plushie.armourers_workshop.core.data.DataManager.connect(DataManager.java:40) ~[?:?]
        ... 12 more

```

更新插件版本后出现的

**Comment by SAGESSE-CN** [comment]
晚点修复

**Comment by SAGESSE-CN** [comment]
fixed in 2.1.2
